import { expect, test, type Page } from "@playwright/test";

const browserErrors = new WeakMap<Page, string[]>();
test.beforeEach(async ({ page }) => {
  const errors: string[] = [];
  browserErrors.set(page, errors);
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); });
  await page.goto("/menu");
  await expect(page.locator("[data-menu-ready=true]")).toBeVisible();
});
test.afterEach(async ({ page }) => { expect(browserErrors.get(page) ?? []).toEqual([]); });
test("search, clear, simple add, and cart persistence", async ({ page }) => { await expect(page.getByRole("heading", { name: "Choose something delicious." })).toBeVisible(); await page.getByLabel("Search the menu").fill("Butter Chicken"); await expect(page).toHaveURL(/q=Butter\+Chicken/); await expect(page.getByRole("heading", { name: "Butter Chicken", exact: true })).toBeVisible(); await page.getByRole("button", { name: "Add Butter Chicken", exact: true }).click(); await expect(page.getByRole("button", { name: /Open cart, 1 items/ })).toBeVisible(); await page.reload(); await expect(page.getByRole("button", { name: /Open cart, 1 items/ })).toBeVisible(); await page.getByLabel("Clear search").click(); await expect(page.getByRole("heading", { name: "Veggie Curry Thali" })).toBeVisible(); });
test("required Saag option is enforced and retained", async ({ page }) => { await page.getByLabel("Search the menu").fill("Saag (Chicken/Goat/Lamb)"); await page.getByRole("button", { name: /Choose options for Saag/ }).click(); await page.getByRole("button", { name: /Add to Cart/ }).click(); await expect(page.getByText("Choose one option before adding this item.")).toBeVisible(); await page.getByText("Goat", { exact: true }).click(); await page.getByRole("button", { name: /Add to Cart/ }).click(); const counter = page.getByRole("group", { name: "Saag (Chicken/Goat/Lamb) quantity" }); await expect(counter).toBeVisible(); await page.getByRole("button", { name: "Increase Saag (Chicken/Goat/Lamb) quantity" }).click(); await expect(counter.locator("output")).toHaveText("2"); await page.getByRole("button", { name: /Open cart, 2 items/ }).click(); await expect(page.getByText("Choose protein: Goat")).toBeVisible(); });
test("checkout validates fields and creates a bookmarkable private order link", async ({ page, browser }) => {
  await page.getByRole("button", { name: "Add Water" }).click(); await page.goto("/checkout"); const place = page.getByRole("button", { name: "Place pickup order" });
  await expect(place).toBeEnabled(); await place.click(); await expect(page.getByText("Enter a name between 2 and 80 characters.")).toBeVisible();
  await page.getByLabel("Name").fill("Checkout Customer"); await page.getByLabel("Email").fill("checkout@example.com"); await page.getByLabel("Phone").fill("905-555-0123"); await expect(page.getByText("CA$1.13")).toBeVisible(); await place.click();
  await expect(page).toHaveURL(/\/order\/[0-9a-f-]{36}#access=[A-Za-z0-9_-]{43}$/); await expect(page.getByRole("heading", { name: "Your order was received" })).toBeVisible();
  await expect(page.getByText(/HOI-\d{6}-[A-F0-9]{6}/)).toBeVisible(); await expect(page.getByText("Payment due at store")).toBeVisible(); await expect(page.getByRole("heading", { name: "Save your order details" })).toBeVisible(); await expect(page.getByText("Take a screenshot", { exact: true })).toBeVisible();
  const privateStatusUrl = page.url(); const cleanContext = await browser.newContext();
  try {
    expect(await cleanContext.cookies()).toHaveLength(0); const orderId = new URL(privateStatusUrl).pathname.split("/").at(-1); const unauthorised = await cleanContext.request.get(new URL(`/api/orders/${orderId}`, privateStatusUrl).toString()); expect(unauthorised.status()).toBe(401);
    const cleanPage = await cleanContext.newPage(); await cleanPage.goto(privateStatusUrl);
    await expect(cleanPage.getByRole("heading", { name: "Your order was received" })).toBeVisible(); await expect(cleanPage.getByRole("heading", { name: "Save your order details" })).toBeVisible();
  } finally { await cleanContext.close(); }
});
test("checkout removes an accepted quote as soon as the cart changes", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "The checkout request-race regression is covered once.");
  await page.getByLabel("Search the menu").fill("Roti");
  await page.getByRole("button", { name: "Add Roti", exact: true }).click();
  await page.getByLabel("Search the menu").fill("Gulab Jamun");
  await page.getByRole("button", { name: "Add Gulab Jamun", exact: true }).click();
  await page.goto("/checkout");
  await expect(page.getByRole("button", { name: "Place pickup order" })).toBeEnabled();
  await page.route("**/api/quote", async (route) => route.fulfill({ status: 204 }));
  await page.getByRole("button", { name: /Open cart, 2 items/ }).click();
  const cart = page.getByRole("dialog", { name: "Cart" });
  const gulab = cart.locator("article.cart-line").filter({ hasText: "Gulab Jamun" });
  await gulab.getByRole("button", { name: "Increase Gulab Jamun quantity" }).click();
  const roti = cart.locator("article.cart-line").filter({ hasText: "Roti" });
  await roti.getByRole("button", { name: "Remove" }).click();
  await cart.getByRole("button", { name: "Close cart" }).click();
  await expect(page.getByText("We could not confirm the order.")).toBeVisible();
  await expect(page.getByRole("button", { name: "Place pickup order" })).toHaveCount(0);
  await expect(page.getByText("1 × Roti")).toHaveCount(0);
});
test("mobile has no page-level horizontal overflow and exposes cart bar", async ({ page }) => { await page.setViewportSize({ width: 320, height: 700 }); await page.getByRole("button", { name: "Add Water" }).click(); await expect(page.getByRole("button", { name: /View Cart/ })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); });
test("mobile category selection stays active while smooth scrolling", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); const chips = page.locator(".category-chips"); const selected = chips.getByRole("link", { name: "Special Combos" }); await selected.click(); const observed = await page.evaluate(async () => { const labels: Array<string | null> = []; for (let sample = 0; sample < 14; sample += 1) { labels.push(document.querySelector(".category-chips a.active")?.textContent?.trim() ?? null); await new Promise((resolve) => window.setTimeout(resolve, 60)); } return labels; }); expect(new Set(observed)).toEqual(new Set(["Special Combos"])); await expect(selected).toHaveClass(/active/); await expect(page.getByRole("heading", { name: "Special Combos", exact: true })).toBeVisible(); });
test("no-result state clears back to the complete menu", async ({ page }) => { await page.getByLabel("Search the menu").fill("definitely not a dish"); await expect(page.getByRole("heading", { name: "No dishes found" })).toBeVisible(); await page.locator(".no-results").getByRole("button", { name: "Clear search" }).click(); await expect(page.getByRole("heading", { name: "Thali", exact: true })).toBeVisible(); });
test("Escape closes a keyboard-opened dialog and restores focus", async ({ page }) => { await page.getByLabel("Search the menu").fill("Saag (Chicken/Goat/Lamb)"); const trigger = page.getByRole("button", { name: /Choose options for Saag/ }); await trigger.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog")).toBeVisible(); await page.keyboard.press("Escape"); await expect(page.getByRole("dialog")).toBeHidden(); await expect(trigger).toBeFocused(); });
test("cart drawer restores focus to its desktop trigger", async ({ page }) => { await page.getByRole("button", { name: "Add Water" }).click(); const trigger = page.getByRole("button", { name: /Open cart, 1 items/ }); await trigger.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog", { name: "Cart" })).toBeVisible(); await page.keyboard.press("Escape"); await expect(page.getByRole("dialog", { name: "Cart" })).toBeHidden(); await expect(trigger).toBeFocused(); });
test("cart order summary aligns on desktop and follows the items on mobile", async ({ page }) => { await page.setViewportSize({ width: 1440, height: 900 }); await page.getByRole("button", { name: "Add Water" }).click(); await page.goto("/cart"); const items = page.locator(".cart-items-panel"); const summary = page.locator(".order-summary"); await expect(items).toBeVisible(); await expect(summary).toBeVisible(); const [itemsBox, summaryBox] = await Promise.all([items.boundingBox(), summary.boundingBox()]); expect(itemsBox).not.toBeNull(); expect(summaryBox).not.toBeNull(); expect(Math.abs(itemsBox!.y - summaryBox!.y)).toBeLessThanOrEqual(1); await expect(summary).toHaveCSS("position", "sticky"); await page.setViewportSize({ width: 390, height: 844 }); await expect(summary).toHaveCSS("position", "static"); const [mobileItemsBox, mobileSummaryBox] = await Promise.all([items.boundingBox(), summary.boundingBox()]); expect(mobileItemsBox).not.toBeNull(); expect(mobileSummaryBox).not.toBeNull(); expect(mobileSummaryBox!.y).toBeGreaterThanOrEqual(mobileItemsBox!.y + mobileItemsBox!.height); });
test("mobile navigation and cart drawer restore focus", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); const navigation = page.getByRole("button", { name: "Open navigation" }); await navigation.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog", { name: "Menu" })).toBeVisible(); await page.keyboard.press("Escape"); await expect(navigation).toBeFocused(); await page.getByRole("button", { name: "Add Water" }).click(); const cartBar = page.locator("#mobile-cart-trigger"); await cartBar.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog", { name: "Cart" })).toBeVisible(); await page.keyboard.press("Escape"); await expect(cartBar).toBeFocused(); });
test("menu quantity counter handles rapid additions and returns to Add at zero", async ({ page }) => { await page.getByRole("button", { name: "Add Water", exact: true }).click(); await expect(page.locator(".status-announcer")).toHaveText("Water added to cart."); const counter = page.getByRole("group", { name: "Water quantity" }); await expect(counter).toBeVisible(); const increase = page.getByRole("button", { name: "Increase Water quantity" }); for (let count = 0; count < 4; count += 1) await increase.click(); await expect(counter.locator("output")).toHaveText("5"); await expect(page.getByRole("button", { name: /Open cart, 5 items/ })).toBeVisible(); await expect(page.locator(".cart-count-pulse").first()).toHaveCSS("animation-name", "cart-pulse"); const decrease = page.getByRole("button", { name: "Decrease Water quantity" }); for (let count = 0; count < 5; count += 1) await decrease.click(); await expect(page.getByRole("button", { name: "Add Water", exact: true })).toBeVisible(); await expect(page.getByRole("button", { name: /Open cart, 0 items/ })).toBeVisible(); });
test("required selections survive responsive changes while the dialog is open", async ({ page }) => { await page.getByLabel("Search the menu").fill("Saag (Chicken/Goat/Lamb)"); const trigger = page.getByRole("button", { name: /Choose options for Saag/ }); await trigger.click(); await page.getByText("Lamb", { exact: true }).click(); await page.setViewportSize({ width: 390, height: 640 }); await expect(page.getByRole("radio", { name: "Lamb" })).toBeChecked(); await expect(page.getByRole("button", { name: /Add to Cart/ })).toBeVisible(); await page.keyboard.press("Escape"); await expect(trigger).toBeFocused(); await page.waitForTimeout(350); await expect(page.locator(".overlay")).toHaveCount(0); });
test("reduced motion exposes final states without entrance or pulse animation", async ({ page }) => { await page.emulateMedia({ reducedMotion: "reduce" }); await page.reload(); await expect(page.locator(".page-hero-copy h1")).toHaveCSS("animation-name", "none"); await page.getByRole("button", { name: "Add Water", exact: true }).click(); await expect(page.locator(".cart-count-pulse").first()).toHaveCSS("animation-name", "none"); await page.getByLabel("Search the menu").fill("Saag (Chicken/Goat/Lamb)"); await page.getByRole("button", { name: /Choose options for Saag/ }).click(); await expect(page.getByRole("dialog")).toHaveCSS("animation-name", "none"); });
test("mobile cart editing transitions between a single overlay and hides the cart bar", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); await page.getByLabel("Search the menu").fill("Saag (Chicken/Goat/Lamb)"); await page.getByRole("button", { name: /Choose options for Saag/ }).click(); await page.getByText("Chicken", { exact: true }).click(); await page.getByRole("button", { name: /Add to Cart/ }).click(); await page.locator("#mobile-cart-trigger").click(); await page.getByRole("button", { name: "Edit", exact: true }).click(); await expect(page.getByRole("dialog", { name: "Saag (Chicken/Goat/Lamb)" })).toBeVisible(); await expect(page.locator(".overlay[data-state=open]")).toHaveCount(1); await expect(page.locator("#mobile-cart-trigger")).toBeHidden(); await page.keyboard.press("Escape"); await expect(page.getByRole("dialog", { name: "Cart" })).toBeVisible(); await expect(page.locator(".overlay[data-state=open]")).toHaveCount(1); });
test("operator sees an order and updates live customer status", async ({ page }, testInfo) => { const customer = `Dashboard ${testInfo.project.name}`; await page.getByRole("button", { name: "Add Water" }).click(); await page.goto("/checkout"); await page.getByLabel("Name").fill(customer); await page.getByLabel("Email").fill(`${testInfo.project.name}@example.com`); await page.getByLabel("Phone").fill("905-555-0199"); await page.getByRole("button", { name: "Place pickup order" }).click(); await expect(page).toHaveURL(/\/order\//); const statusUrl = page.url(); await page.waitForLoadState("networkidle"); await page.goto("/operator/login"); await page.getByLabel("Operator email").fill("owner@example.com"); await page.getByLabel("Password").fill("test-password-123"); await page.getByRole("button", { name: "Sign in" }).click(); await expect(page.getByRole("heading", { name: "Operator dashboard" })).toBeVisible(); await page.getByRole("link", { name: /Open pickup orders/ }).click(); await expect(page.getByRole("heading", { name: "Pickup orders" })).toBeVisible(); const card = page.locator("article.operator-order").filter({ hasText: customer }).first(); await expect(card).toBeVisible(); await card.getByLabel("Kitchen status").selectOption("ready_for_pickup"); await expect(card.getByText("Ready for pickup", { exact: true }).first()).toBeVisible(); await card.getByRole("button", { name: "Mark paid at store" }).click(); await expect(card.getByRole("button", { name: "Paid at store" })).toBeVisible(); await page.waitForLoadState("networkidle"); await page.goto(statusUrl); await expect(page.getByRole("heading", { name: "Your order is ready for pickup" })).toBeVisible(); await expect(page.getByText("Paid at store", { exact: true })).toBeVisible(); });
test("operator order list refreshes itself when a customer places an order", async ({ page, context }, testInfo) => {
  await page.goto("/operator/login"); await page.getByLabel("Operator email").fill("owner@example.com"); await page.getByLabel("Password").fill("test-password-123"); await page.getByRole("button", { name: "Sign in" }).click(); await expect(page.getByRole("heading", { name: "Operator dashboard" })).toBeVisible(); await page.goto("/operator/orders");
  await expect(page.locator(".operator-status-bar").filter({ hasText: "Auto-refresh is on · every 5 seconds" }).first()).toBeVisible(); const customer = `Auto refresh ${testInfo.project.name}`; const customerPage = await context.newPage();
  try {
    await customerPage.goto("/menu"); await customerPage.getByRole("button", { name: "Add Water", exact: true }).click(); await customerPage.goto("/checkout"); await customerPage.getByLabel("Name").fill(customer); await customerPage.getByLabel("Email").fill(`auto-${testInfo.project.name}@example.com`); await customerPage.getByLabel("Phone").fill("905-555-0188"); await customerPage.getByRole("button", { name: "Place pickup order" }).click(); await expect(customerPage.getByRole("heading", { name: "Your order was received" })).toBeVisible();
    await expect(page.locator("article.operator-order").filter({ hasText: customer })).toBeVisible({ timeout: 12_000 });
  } finally { await customerPage.close(); }
});
test("operator hub keeps every operator destination in one protected navigation", async ({ page }) => { await page.goto("/operator/login"); await page.getByLabel("Operator email").fill("owner@example.com"); await page.getByLabel("Password").fill("test-password-123"); await page.getByRole("button", { name: "Sign in" }).click(); await expect(page.getByRole("heading", { name: "Operator dashboard" })).toBeVisible(); const nav = page.getByRole("navigation", { name: "Operator navigation" }); await expect(nav.getByRole("link", { name: "Overview" })).toHaveAttribute("aria-current", "page"); await expect(nav.getByRole("link", { name: "Orders" })).toBeVisible(); await expect(nav.getByRole("link", { name: "Edit Menu" })).toBeVisible(); await expect(nav.getByRole("link", { name: "Settings" })).toBeVisible(); await expect(nav.getByRole("link", { name: "Notifications" })).toBeVisible(); await expect(nav.getByRole("link", { name: "View website" })).toBeVisible(); await nav.getByRole("link", { name: "Edit Menu" }).click(); await expect(page).toHaveURL(/\/operator\/menu$/); await expect(page.getByRole("heading", { name: "Menu management" })).toBeVisible(); await expect(nav.getByRole("link", { name: "Edit Menu" })).toHaveAttribute("aria-current", "page"); await nav.getByRole("link", { name: "Notifications" }).click(); await expect(page).toHaveURL(/\/operator\/notifications$/); await expect(page.getByRole("heading", { name: "Notifications", exact: true })).toBeVisible(); await expect(nav.getByRole("link", { name: "Notifications" })).toHaveAttribute("aria-current", "page"); await nav.getByRole("link", { name: "Settings" }).click(); await expect(page.getByRole("heading", { name: "Ordering settings" })).toBeVisible(); await expect(nav).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); });
test("operator can edit a menu item and the public menu uses the trusted update", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "The storage mutation is covered once to avoid cross-browser write races.");
  await page.goto("/operator/login");
  await page.getByLabel("Operator email").fill("owner@example.com");
  await page.getByLabel("Password").fill("test-password-123");
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page.getByRole("heading", { name: "Operator dashboard" })).toBeVisible();
  await page.goto("/operator/menu");
  await expect(page.getByRole("heading", { name: "Menu items" })).toBeVisible();
  await page.getByLabel("Search menu items").fill("Montreal Spl. Poutine");
  const editor = page.locator("form.menu-editor-row", { has: page.locator("#menu-name-appetizers-montreal-spl-poutine") });
  await expect(editor).toBeVisible();
  await editor.getByLabel("Item name").fill("Montreal Special Poutine");
  await editor.getByLabel("Price (CAD)").fill("9.49");
  await editor.getByLabel("Ordering availability").selectOption("unavailable");
  await editor.getByRole("button", { name: "Save item" }).click();
  await expect(editor.getByText("Montreal Special Poutine was updated.")).toBeVisible();

  await page.goto("/menu?q=Montreal+Special+Poutine");
  const card = page.locator("article.menu-card").filter({ hasText: "Montreal Special Poutine" });
  await expect(card).toBeVisible();
  await expect(card.getByText("CA$9.49")).toBeVisible();
  await expect(card.getByRole("button", { name: "Unavailable" })).toBeDisabled();

  await page.goto("/operator/menu");
  await page.getByLabel("Search menu items").fill("Montreal Special Poutine");
  const restore = page.locator("form.menu-editor-row", { has: page.locator("#menu-name-appetizers-montreal-spl-poutine") });
  await restore.getByLabel("Item name").fill("Montreal Spl. Poutine");
  await restore.getByLabel("Price (CAD)").fill("8.99");
  await restore.getByLabel("Ordering availability").selectOption("available");
  await restore.getByRole("button", { name: "Save item" }).click();
  await expect(restore.getByText("Montreal Spl. Poutine was updated.")).toBeVisible();
});
