import { expect, test, type Page } from "@playwright/test";

const browserErrors = new WeakMap<Page, string[]>();
test.beforeEach(async ({ page }) => {
  const errors: string[] = [];
  browserErrors.set(page, errors);
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); });
  await page.goto("/menu");
  await expect(page.locator("[data-menu-ready=true]")).toBeVisible();
});
test.afterEach(async ({ page }) => { expect(browserErrors.get(page) ?? []).toEqual([]); });
test("search, clear, simple add, and cart persistence", async ({ page }) => { await expect(page.getByRole("heading", { name: "Choose something delicious." })).toBeVisible(); await page.getByLabel("Search the menu").fill("Butter Chicken"); await expect(page).toHaveURL(/q=Butter\+Chicken/); await expect(page.getByRole("heading", { name: "Butter Chicken", exact: true })).toBeVisible(); await page.getByRole("button", { name: "Add Butter Chicken", exact: true }).click(); await expect(page.getByRole("button", { name: /Open cart, 1 items/ })).toBeVisible(); await page.reload(); await expect(page.getByRole("button", { name: /Open cart, 1 items/ })).toBeVisible(); await page.getByLabel("Clear search").click(); await expect(page.getByRole("heading", { name: "Veggie Curry Thali" })).toBeVisible(); });
test("required Saag option is enforced and retained", async ({ page }) => { await page.getByLabel("Search the menu").fill("Saag (Chicken/Goat/Lamb)"); await page.getByRole("button", { name: /Choose options for Saag/ }).click(); await page.getByRole("button", { name: /Add to Cart/ }).click(); await expect(page.getByText("Choose one option before adding this item.")).toBeVisible(); await page.getByText("Goat", { exact: true }).click(); await page.getByRole("button", { name: /Add to Cart/ }).click(); await page.getByRole("button", { name: /Open cart, 1 items/ }).click(); await expect(page.getByText("Choose protein: Goat")).toBeVisible(); });
test("checkout validates fields and stays gated", async ({ page }) => { await page.getByRole("button", { name: "Add Water" }).click(); await page.goto("/checkout"); await expect(page.getByText(/Online payment is not available yet/)).toBeVisible(); await expect(page.getByRole("button", { name: "Continue to secure payment" })).toBeDisabled(); });
test("mobile has no page-level horizontal overflow and exposes cart bar", async ({ page }) => { await page.setViewportSize({ width: 320, height: 700 }); await page.getByRole("button", { name: "Add Water" }).click(); await expect(page.getByRole("button", { name: /View Cart/ })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); });
test("no-result state clears back to the complete menu", async ({ page }) => { await page.getByLabel("Search the menu").fill("definitely not a dish"); await expect(page.getByRole("heading", { name: "No dishes found" })).toBeVisible(); await page.locator(".no-results").getByRole("button", { name: "Clear search" }).click(); await expect(page.getByRole("heading", { name: "Thali", exact: true })).toBeVisible(); });
test("Escape closes a keyboard-opened dialog and restores focus", async ({ page }) => { await page.getByLabel("Search the menu").fill("Saag (Chicken/Goat/Lamb)"); const trigger = page.getByRole("button", { name: /Choose options for Saag/ }); await trigger.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog")).toBeVisible(); await page.keyboard.press("Escape"); await expect(page.getByRole("dialog")).toBeHidden(); await expect(trigger).toBeFocused(); });
test("cart drawer restores focus to its desktop trigger", async ({ page }) => { await page.getByRole("button", { name: "Add Water" }).click(); const trigger = page.getByRole("button", { name: /Open cart, 1 items/ }); await trigger.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog", { name: "Cart" })).toBeVisible(); await page.keyboard.press("Escape"); await expect(page.getByRole("dialog", { name: "Cart" })).toBeHidden(); await expect(trigger).toBeFocused(); });
test("mobile navigation and cart drawer restore focus", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); const navigation = page.getByRole("button", { name: "Open navigation" }); await navigation.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog", { name: "Menu" })).toBeVisible(); await page.keyboard.press("Escape"); await expect(navigation).toBeFocused(); await page.getByRole("button", { name: "Add Water" }).click(); const cartBar = page.locator("#mobile-cart-trigger"); await cartBar.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog", { name: "Cart" })).toBeVisible(); await page.keyboard.press("Escape"); await expect(cartBar).toBeFocused(); });
