import { expect, test, type Page } from "@playwright/test";

const browserErrors = new WeakMap<Page, string[]>();
test.beforeEach(async ({ page }) => {
  const errors: string[] = [];
  browserErrors.set(page, errors);
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); });
  await page.goto("/menu");
  await expect(page.locator("[data-menu-ready=true]")).toBeVisible();
});
test.afterEach(async ({ page }) => { expect(browserErrors.get(page) ?? []).toEqual([]); });
test("search, clear, simple add, and cart persistence", async ({ page }) => { await expect(page.getByRole("heading", { name: "Choose something delicious." })).toBeVisible(); await page.getByLabel("Search the menu").fill("Butter Chicken"); await expect(page).toHaveURL(/q=Butter\+Chicken/); await expect(page.getByRole("heading", { name: "Butter Chicken", exact: true })).toBeVisible(); await page.getByRole("button", { name: "Add Butter Chicken", exact: true }).click(); await expect(page.getByRole("button", { name: /Open cart, 1 items/ })).toBeVisible(); await page.reload(); await expect(page.getByRole("button", { name: /Open cart, 1 items/ })).toBeVisible(); await page.getByLabel("Clear search").click(); await expect(page.getByRole("heading", { name: "Veggie Curry Thali" })).toBeVisible(); });
test("required Saag option is enforced and retained", async ({ page }) => { await page.getByLabel("Search the menu").fill("Saag (Chicken/Goat/Lamb)"); await page.getByRole("button", { name: /Choose options for Saag/ }).click(); await page.getByRole("button", { name: /Add to Cart/ }).click(); await expect(page.getByText("Choose one option before adding this item.")).toBeVisible(); await page.getByText("Goat", { exact: true }).click(); await page.getByRole("button", { name: /Add to Cart/ }).click(); const counter = page.getByRole("group", { name: "Saag (Chicken/Goat/Lamb) quantity" }); await expect(counter).toBeVisible(); await page.getByRole("button", { name: "Increase Saag (Chicken/Goat/Lamb) quantity" }).click(); await expect(counter.locator("output")).toHaveText("2"); await page.getByRole("button", { name: /Open cart, 2 items/ }).click(); await expect(page.getByText("Choose protein: Goat")).toBeVisible(); });
test("checkout validates fields and stays gated", async ({ page }) => { await page.getByRole("button", { name: "Add Water" }).click(); await page.goto("/checkout"); await expect(page.getByText(/Online payment is not available yet/)).toBeVisible(); await expect(page.getByRole("button", { name: "Continue to secure payment" })).toBeDisabled(); });
test("mobile has no page-level horizontal overflow and exposes cart bar", async ({ page }) => { await page.setViewportSize({ width: 320, height: 700 }); await page.getByRole("button", { name: "Add Water" }).click(); await expect(page.getByRole("button", { name: /View Cart/ })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); });
test("mobile category selection stays active while smooth scrolling", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); const chips = page.locator(".category-chips"); const selected = chips.getByRole("link", { name: "Special Combos" }); await selected.click(); const observed = await page.evaluate(async () => { const labels: Array<string | null> = []; for (let sample = 0; sample < 14; sample += 1) { labels.push(document.querySelector(".category-chips a.active")?.textContent?.trim() ?? null); await new Promise((resolve) => window.setTimeout(resolve, 60)); } return labels; }); expect(new Set(observed)).toEqual(new Set(["Special Combos"])); await expect(selected).toHaveClass(/active/); await expect(page.getByRole("heading", { name: "Special Combos", exact: true })).toBeVisible(); });
test("no-result state clears back to the complete menu", async ({ page }) => { await page.getByLabel("Search the menu").fill("definitely not a dish"); await expect(page.getByRole("heading", { name: "No dishes found" })).toBeVisible(); await page.locator(".no-results").getByRole("button", { name: "Clear search" }).click(); await expect(page.getByRole("heading", { name: "Thali", exact: true })).toBeVisible(); });
test("Escape closes a keyboard-opened dialog and restores focus", async ({ page }) => { await page.getByLabel("Search the menu").fill("Saag (Chicken/Goat/Lamb)"); const trigger = page.getByRole("button", { name: /Choose options for Saag/ }); await trigger.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog")).toBeVisible(); await page.keyboard.press("Escape"); await expect(page.getByRole("dialog")).toBeHidden(); await expect(trigger).toBeFocused(); });
test("cart drawer restores focus to its desktop trigger", async ({ page }) => { await page.getByRole("button", { name: "Add Water" }).click(); const trigger = page.getByRole("button", { name: /Open cart, 1 items/ }); await trigger.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog", { name: "Cart" })).toBeVisible(); await page.keyboard.press("Escape"); await expect(page.getByRole("dialog", { name: "Cart" })).toBeHidden(); await expect(trigger).toBeFocused(); });
test("mobile navigation and cart drawer restore focus", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); const navigation = page.getByRole("button", { name: "Open navigation" }); await navigation.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog", { name: "Menu" })).toBeVisible(); await page.keyboard.press("Escape"); await expect(navigation).toBeFocused(); await page.getByRole("button", { name: "Add Water" }).click(); const cartBar = page.locator("#mobile-cart-trigger"); await cartBar.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog", { name: "Cart" })).toBeVisible(); await page.keyboard.press("Escape"); await expect(cartBar).toBeFocused(); });
test("menu quantity counter handles rapid additions and returns to Add at zero", async ({ page }) => { await page.getByRole("button", { name: "Add Water", exact: true }).click(); await expect(page.locator(".status-announcer")).toHaveText("Water added to cart."); const counter = page.getByRole("group", { name: "Water quantity" }); await expect(counter).toBeVisible(); const increase = page.getByRole("button", { name: "Increase Water quantity" }); for (let count = 0; count < 4; count += 1) await increase.click(); await expect(counter.locator("output")).toHaveText("5"); await expect(page.getByRole("button", { name: /Open cart, 5 items/ })).toBeVisible(); await expect(page.locator(".cart-count-pulse").first()).toHaveCSS("animation-name", "cart-pulse"); const decrease = page.getByRole("button", { name: "Decrease Water quantity" }); for (let count = 0; count < 5; count += 1) await decrease.click(); await expect(page.getByRole("button", { name: "Add Water", exact: true })).toBeVisible(); await expect(page.getByRole("button", { name: /Open cart, 0 items/ })).toBeVisible(); });
test("required selections survive responsive changes while the dialog is open", async ({ page }) => { await page.getByLabel("Search the menu").fill("Saag (Chicken/Goat/Lamb)"); const trigger = page.getByRole("button", { name: /Choose options for Saag/ }); await trigger.click(); await page.getByText("Lamb", { exact: true }).click(); await page.setViewportSize({ width: 390, height: 640 }); await expect(page.getByRole("radio", { name: "Lamb" })).toBeChecked(); await expect(page.getByRole("button", { name: /Add to Cart/ })).toBeVisible(); await page.keyboard.press("Escape"); await expect(trigger).toBeFocused(); await page.waitForTimeout(350); await expect(page.locator(".overlay")).toHaveCount(0); });
test("reduced motion exposes final states without entrance or pulse animation", async ({ page }) => { await page.emulateMedia({ reducedMotion: "reduce" }); await page.reload(); await expect(page.locator(".page-hero-copy h1")).toHaveCSS("animation-name", "none"); await page.getByRole("button", { name: "Add Water", exact: true }).click(); await expect(page.locator(".cart-count-pulse").first()).toHaveCSS("animation-name", "none"); await page.getByLabel("Search the menu").fill("Saag (Chicken/Goat/Lamb)"); await page.getByRole("button", { name: /Choose options for Saag/ }).click(); await expect(page.getByRole("dialog")).toHaveCSS("animation-name", "none"); });
test("mobile cart editing transitions between a single overlay and hides the cart bar", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); await page.getByLabel("Search the menu").fill("Saag (Chicken/Goat/Lamb)"); await page.getByRole("button", { name: /Choose options for Saag/ }).click(); await page.getByText("Chicken", { exact: true }).click(); await page.getByRole("button", { name: /Add to Cart/ }).click(); await page.locator("#mobile-cart-trigger").click(); await page.getByRole("button", { name: "Edit", exact: true }).click(); await expect(page.getByRole("dialog", { name: "Saag (Chicken/Goat/Lamb)" })).toBeVisible(); await expect(page.locator(".overlay[data-state=open]")).toHaveCount(1); await expect(page.locator("#mobile-cart-trigger")).toBeHidden(); await page.keyboard.press("Escape"); await expect(page.getByRole("dialog", { name: "Cart" })).toBeVisible(); await expect(page.locator(".overlay[data-state=open]")).toHaveCount(1); });
test("cancelled checkout waits for backend reconciliation before enabling retry", async ({ page }) => { let releaseStatus!: () => void; const statusGate = new Promise<void>((resolve) => { releaseStatus = resolve; }); await page.route("**/api/orders/**", async (route) => { await statusGate; await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ paymentStatus: "pending_payment" }) }); }); await page.goto("/order/11111111-1111-4111-8111-111111111111?cancelled=1"); await expect(page.locator('.confirmation-card > p[aria-live="polite"]:visible').first()).toContainText("We are checking Stripe"); await expect(page.getByRole("link", { name: "Return to checkout" })).toHaveCount(0); releaseStatus(); await expect(page.locator(".confirmation-card > p:visible").filter({ hasText: "No successful payment has been confirmed" }).first()).toBeVisible(); await expect(page.getByRole("link", { name: "Return to checkout" }).filter({ visible: true })).toBeVisible(); });
