"use client";
import { CheckCircle2, Clock3, CircleX } from "lucide-react";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useCart } from "@/components/cart-provider";
import { formatCad } from "@/lib/menu";

type OrderStatus = { id: string; orderNumber: string; paymentStatus: "pending_payment" | "paid" | "expired" | "payment_failed"; fulfillmentStatus: string; createdAt: string; paidAt: string | null; customerName: string; customerEmail: string; customerPhone: string; customerNotes: string | null; pickupAddress: Record<string, string>; pickupEstimateText: string | null; subtotalCents: number; taxCents: number; feeCents: number; totalCents: number; cartSnapshot: Array<{ lineId: string; itemId: string; quantity: number }>; lines: Array<{ lineId: string; name: string; quantity: number; selections: Array<{ groupId: string; groupLabel: string; optionName: string }>; lineTotalCents: number }> };

export function OrderStatusClient({ orderId, cancelled }: { orderId: string; cancelled: boolean }) {
  const cart = useCart(); const [order, setOrder] = useState<OrderStatus | null>(null); const [error, setError] = useState(""); const [checking, setChecking] = useState(true); const cleared = useRef(false);
  const clearPurchasedSnapshot = cart.clearPurchasedSnapshot;
  useEffect(() => { let stopped = false; let timeout: ReturnType<typeof setTimeout>; let attempts = 0; async function check() { try { const response = await fetch(`/api/orders/${orderId}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Order status could not be loaded."); if (stopped) return; setOrder(data); setError(""); setChecking(false); if (data.paymentStatus === "paid" && !cleared.current) { clearPurchasedSnapshot(data.cartSnapshot); cleared.current = true; } if (data.paymentStatus === "pending_payment" && attempts++ < 20) timeout = setTimeout(check, Math.min(8000, 1500 + attempts * 500)); } catch (caught) { if (!stopped) { setError(caught instanceof Error ? caught.message : "Order status could not be loaded."); setChecking(false); } } } check(); return () => { stopped = true; clearTimeout(timeout); }; }, [orderId, clearPurchasedSnapshot]);
  const paid = order?.paymentStatus === "paid"; const failed = order && ["expired", "payment_failed"].includes(order.paymentStatus);
  return <main className="container confirmation-page"><section className="confirmation-card">{paid ? <CheckCircle2 className="status-icon success" size={54} /> : failed || cancelled ? <CircleX className="status-icon failure" size={54} /> : <Clock3 className="status-icon pending" size={54} />}<span className="eyebrow">{paid ? "Payment confirmed" : failed ? "Payment not completed" : cancelled ? "Checkout cancelled" : "Checking payment"}</span><h1 className="section-title">{paid ? "Thank you for your order" : failed || cancelled ? "Your cart is still here" : "Confirming your payment"}</h1>{checking && <p aria-live="polite">We are checking Stripe and the restaurant’s order record. This can take a few moments.</p>}{error && <div className="inline-error" role="alert"><strong>Status unavailable</strong><span>{error}</span><button className="text-action" onClick={() => location.reload()}>Try again</button></div>}{paid && order && <><p>Payment for order <strong>{order.orderNumber}</strong> is confirmed. This does not yet mean the kitchen has accepted the order.</p><div className="pickup-box"><strong>Pickup location</strong><span>{order.pickupAddress.street}, {order.pickupAddress.city}, {order.pickupAddress.province} {order.pickupAddress.postalCode}</span>{order.pickupEstimateText && <span>{order.pickupEstimateText}</span>}</div><div className="confirmation-receipt"><h2 className="display">Receipt</h2>{order.lines.map((line) => <div className="receipt-line" key={line.lineId}><div><strong>{line.quantity} × {line.name}</strong>{line.selections.map((selection) => <small key={selection.groupId}>{selection.groupLabel}: {selection.optionName}</small>)}</div><strong>{formatCad(line.lineTotalCents)}</strong></div>)}<div className="summary-row"><span>Subtotal</span><strong>{formatCad(order.subtotalCents)}</strong></div><div className="summary-row"><span>Tax</span><strong>{formatCad(order.taxCents)}</strong></div>{order.feeCents > 0 && <div className="summary-row"><span>Fees</span><strong>{formatCad(order.feeCents)}</strong></div>}<div className="summary-row summary-total"><span>Total paid</span><strong>{formatCad(order.totalCents)}</strong></div></div></>}{!paid && (failed || cancelled) && <p>No successful payment has been confirmed for this attempt. Review your cart and try again when ready.</p>}<div className="hero-actions">{!paid && <Link className="button-primary" href="/checkout">Return to checkout</Link>}<Link className="button-secondary" href="/menu">Back to menu</Link></div></section></main>;
}
