"use client";
import { ShieldCheck, Trash2 } from "lucide-react";
import { useState } from "react";
import { formatTorontoDate } from "@/lib/date-format";

type Summary = { retentionDays: number; eligible: Array<{ id: string; orderNumber: string; createdAt: string; fulfillmentStatus: string; customerName: string }> };
export function RetentionManager({ initial }: { initial: Summary }) {
  const [summary, setSummary] = useState(initial); const [confirmation, setConfirmation] = useState(""); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function clean() { setPending(true); setError(""); setMessage(""); try { const response = await fetch("/api/operator/data-retention", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmation }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Cleanup failed."); setSummary(data.summary); setConfirmation(""); setMessage(`${data.redactedCount} order record${data.redactedCount === 1 ? " was" : "s were"} de-identified. An evidence entry was written to DataMaintenance.`); } catch (caught) { setError(caught instanceof Error ? caught.message : "Cleanup failed."); } finally { setPending(false); } }
  return <section className="operator-card retention-card"><div className="menu-editor-heading"><div><span className="eyebrow">Privacy operations</span><h2>Customer data retention</h2><p>Completed and cancelled orders become eligible {summary.retentionDays} days after they were placed. Cleanup removes the customer name, email, phone, notes, and private-link access while preserving totals and menu snapshots for accounting.</p></div><ShieldCheck aria-hidden="true" /></div><div className="retention-summary"><strong>{summary.eligible.length} eligible order{summary.eligible.length === 1 ? "" : "s"}</strong>{summary.eligible.slice(0, 20).map((order) => <span key={order.id}>{order.orderNumber} · {formatTorontoDate(order.createdAt)} · {order.customerName}</span>)}{summary.eligible.length > 20 && <span>…and {summary.eligible.length - 20} more</span>}</div><div className="field"><label htmlFor="retention-confirmation">Type DELETE ELIGIBLE CUSTOMER DATA to confirm</label><input id="retention-confirmation" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="off" /></div>{error && <p className="field-error" role="alert">{error}</p>}{message && <p className="pickup-box" role="status">{message}</p>}<button className="button-primary" type="button" disabled={pending || !summary.eligible.length || confirmation !== "DELETE ELIGIBLE CUSTOMER DATA"} onClick={clean}><Trash2 size={18} /> {pending ? "Removing customer data…" : "Remove eligible customer data"}</button></section>;
}
